VIA_ENABLE = yes
VIAL_ENABLE = yes
ENCODER_ENABLE = yes
VIAL_ENCODERS_ENABLE = yes
OLED_ENABLE = yes
OLED_DRIVER = SSD1306
EXTRAKEY_ENABLE = yes
SRC += oled-luna.c
WPM_ENABLE = yes
TAP_DANCE_ENABLE = yes

COMBO_ENABLE = no
GRAVE_ESC_ENABLE = no 
MAGIC_ENABLE = no
MOUSEKEY_ENABLE = no
COMMAND_ENABLE = no
CONSOLE_ENABLE = no
BOOTMAGIC_ENABLE = no


QMK_SETTINGS = yes
LTO_ENABLE = yes
KEY_OVERRIDE_ENABLE = no